server:
  port: 1234
spring:
  datasource:
   url:  jdbc:mysql://localhost:3306/javabatch
   username: root
   password: Temp1234
  jpa:
   hibernate:
    ddl-auto: update
  application:
    name: coupon-service
   
 Server:
    port: 5654
