server:
  port: 2222

spring:
  datasource:
    password: Ambika@91
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL5Dialect



management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
        - beans
      base-path: /myactuator
      
      
  info:
    env:
      enabled: true
      
       
#info:
#  createdBy: Ambika
#  modifiedOn: 22ndjune2022
  

 
  
logging:
  level:
    com:
     zensar: debug
  
        